### ISSUE TITLE
Failing in non git repo folders

### ISSUE THREAD

**Issue by SonnyAD** [inigolabs/revgen#43]
Hello, 
I was trying to display the help of the tool. 
But from a non-git repo. And it fails with a panic like that. 
```
$ revgen help
panic: exit status 128

goroutine 1 [running]:
github.com/inigolabs/revgen/revgen.check(...)
        C:/Users/Sonny/go/pkg/mod/github.com/inigolabs/revgen@v0.3.0/revgen/helpers.go:182
github.com/inigolabs/revgen/revgen.findRootDir({0x785285, 0xb})
        C:/Users/Sonny/go/pkg/mod/github.com/inigolabs/revgen@v0.3.0/revgen/app.go:120 +0x1d1
github.com/inigolabs/revgen/revgen.MakeApp({0xc00016e000, 0x76})
        C:/Users/Sonny/go/pkg/mod/github.com/inigolabs/revgen@v0.3.0/revgen/app.go:30 +0x9c
main.main()
        C:/Users/Sonny/go/pkg/mod/github.com/inigolabs/revgen@v0.3.0/main.go:20 +0x4a
```
It would be better to allow display help or version from anywhere, but also I am wondering does that mean git is a requirement? 

Cheers.

**Comment by SonnyAD** [comment]
Maybe as a different approach to using git you could try to find the closest go.mod file in the parent hierarchy.
